<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class PendudukMiskinSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
[
        'id' => Str::uuid(),
        'nama' => 'Asmarina',
        'alamat' => 'Jl. Bangdes Okura',
        'nama_kepala_keluarga' => 'Suryo Muryadi',
        'jml_agt_keluarga' => 4,
        'kelompokPKH' => 'Cahaya Ilahi',
        'longitude' => 101.520241,
        'latitude' => 0.604874,
        'foto_rumah' => 'dokumen/rumah_pkh/Asmarina.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Asrina',
        'alamat' => 'Jl. Bangdes Okura',
        'nama_kepala_keluarga' => null,
        'jml_agt_keluarga' => 4,
        'kelompokPKH' => 'Cahaya Ilahi',
        'longitude' => 101.51957,
        'latitude' => 0.604403,
        'foto_rumah' => 'dokumen/rumah_pkh/Asrina.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Dahlia',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => 'Jamadi',
        'jml_agt_keluarga' => 4,
        'kelompokPKH' => 'Karmi',
        'longitude' => 101.538234,
        'latitude' => 0.571082,
        'foto_rumah' => 'dokumen/rumah_pkh/Dahlia.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Delvi Susanti',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => 'Sumarlin',
        'jml_agt_keluarga' => 5,
        'kelompokPKH' => 'Mawar',
        'longitude' => 101.530038,
        'latitude' => 0.594083,
        'foto_rumah' => 'dokumen/rumah_pkh/Delvi Susanti.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Dewi rahayu',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => 'Ali Amran',
        'jml_agt_keluarga' => 6,
        'kelompokPKH' => 'Karmi',
        'longitude' => 101.534098,
        'latitude' => 0.575942,
        'foto_rumah' => 'dokumen/rumah_pkh/Dewi Rahayu.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Eka putri',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => 'Dikin Irfan',
        'jml_agt_keluarga' => 4,
        'kelompokPKH' => 'Wardini',
        'longitude' => 101.533938,
        'latitude' => 0.576108,
        'foto_rumah' => 'dokumen/rumah_pkh/Eka Putri.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Eli Suanti',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => 'Jasrul',
        'jml_agt_keluarga' => 5,
        'kelompokPKH' => 'Mawar',
        'longitude' => 101.511303,
        'latitude' => 0.59112,
        'foto_rumah' => 'dokumen/rumah_pkh/Eli Suanti.jpg',
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Elmayana',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => 'Ahmad Saprijon',
        'jml_agt_keluarga' => 6,
        'kelompokPKH' => 'Karmi',
        'longitude' => 101.547836,
        'latitude' => 0.574484,
        'foto_rumah' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Emilia',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => null,
        'jml_agt_keluarga' => null,
        'kelompokPKH' => 'Karmi',
        'longitude' => null,
        'latitude' => null,
        'foto_rumah' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Ernawati',
        'alamat' => 'Jl. SMPN 28',
        'nama_kepala_keluarga' => 'Syamsuri',
        'jml_agt_keluarga' => 5,
        'kelompokPKH' => 'Mawar',
        'longitude' => 101.530232,
        'latitude' => 0.591628,
        'foto_rumah' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Fika Jurahmi',
        'alamat' => 'Jl. Bangdes Okura',
        'nama_kepala_keluarga' => null,
        'jml_agt_keluarga' => 4,
        'kelompokPKH' => 'Cahaya Ilahi',
        'longitude' => 101.520226,
        'latitude' => 0.605844,
        'foto_rumah' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Fitriana',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => 'Robi',
        'jml_agt_keluarga' => 6,
        'kelompokPKH' => 'Karmi',
        'longitude' => 101.544602,
        'latitude' => 0.571628,
        'foto_rumah' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Helmi',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => 'M Nuriyadi',
        'jml_agt_keluarga' => 3,
        'kelompokPKH' => 'Mawar',
        'longitude' => 101.507225,
        'latitude' => 0.591558,
        'foto_rumah' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Ibat Asni',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => 'Abel Indra',
        'jml_agt_keluarga' => 4,
        'kelompokPKH' => 'Karmi',
        'longitude' => 101.545587,
        'latitude' => 0.576401,
        'foto_rumah' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Ica',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => null,
        'jml_agt_keluarga' => 3,
        'kelompokPKH' => 'Wardini',
        'longitude' => 101.547718,
        'latitude' => 0.576977,
        'foto_rumah' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
[
        'id' => Str::uuid(),
        'nama' => 'Juminten',
        'alamat' => 'Jl. Raja Panjang Okura',
        'nama_kepala_keluarga' => 'Joni Saragih',
        'jml_agt_keluarga' => 6,
        'kelompokPKH' => 'Cahaya Ilahi',
        'longitude' => 101.500653,
        'latitude' => 0.59113,
        'foto_rumah' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
    'id' => Str::uuid(),
    'nama' => 'Jurianto',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => null,
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Wardini',
    'longitude' => 101.533923,
    'latitude' => 0.576018,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Kamsiah',
    'alamat' => 'Jl. Bangdes Okura',
    'nama_kepala_keluarga' => '',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Cahaya Ilahi',
    'longitude' => 101.520226,
    'latitude' => 0.605844,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Kana Eni',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Mulyono',
    'jml_agt_keluarga' => 7,
    'kelompokPKH' => 'Cahaya Ilahi',
    'longitude' => 101.496109,
    'latitude' => 0.592791,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Karmi(Ketua Kelompok)',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => '',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.546033,
    'latitude' => 0.571024,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Kurniawati',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Syahrieka',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Cahaya Ilahi',
    'longitude' => 101.489773,
    'latitude' => 0.586474,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Lasiyem',
    'alamat' => 'Jl. Bangdes Okura',
    'nama_kepala_keluarga' => '-',
    'jml_agt_keluarga' => null,
    'kelompokPKH' => 'Cahaya Ilahi',
    'longitude' => null,
    'latitude' => null,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Lastri Yulita',
    'alamat' => 'Jl. Bangdes',
    'nama_kepala_keluarga' => 'Rendy Yusuf',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Mawar',
    'longitude' => 101.511303,
    'latitude' => 0.591120,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Leni Marlina',
    'alamat' => 'Jl. Padat Karya',
    'nama_kepala_keluarga' => 'Pangadilan',
    'jml_agt_keluarga' => 6,
    'kelompokPKH' => 'Mawar',
    'longitude' => null,
    'latitude' => null,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Lestari',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => '',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Wardini',
    'longitude' => 101.5340023,
    'latitude' => 0.5769944,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Lismawati',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => '',
    'jml_agt_keluarga' => null,
    'kelompokPKH' => 'Karmi',
    'longitude' => null,
    'latitude' => null,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Marianti',
    'alamat' => 'Jl. Bangdes Okura',
    'nama_kepala_keluarga' => 'Muhammad Ismail',
    'jml_agt_keluarga' => 3,
    'kelompokPKH' => 'Mawar',
    'longitude' => 101.513312,
    'latitude' => 0.610095,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Misrawati',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Sunardi',
    'jml_agt_keluarga' => 6,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.533156,
    'latitude' => 0.578317,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Misrianti',
    'alamat' => 'Jl. Bangdes perumahan 50',
    'nama_kepala_keluarga' => 'Hendra',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Mawar',
    'longitude' => 101.520280,
    'latitude' => 0.605835,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Murni',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Mardianto',
    'jml_agt_keluarga' => 6,
    'kelompokPKH' => 'Wardini',
    'longitude' => 101.534175,
    'latitude' => 0.576339,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Normah',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => '-',
    'jml_agt_keluarga' => 2,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.537714,
    'latitude' => 0.571245,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Nur Afni',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => '-',
    'jml_agt_keluarga' => 8,
    'kelompokPKH' => 'Cahaya Ilahi',
    'longitude' => 101.510532,
    'latitude' => 0.590098,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Nurcaya (Ketua Kelompok)',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Amaludianto',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Cahaya Ilahi',
    'longitude' => 101.526027,
    'latitude' => 0.592630,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Paini (Ketua Kelompok)',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Suyanto',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Mawar',
    'longitude' => 101.529890,
    'latitude' => 0.592542,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Pilamardianti',
    'alamat' => 'Jl. Bangdes perumahan 50',
    'nama_kepala_keluarga' => 'Jon Hendri',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Mawar',
    'longitude' => 101.520226,
    'latitude' => 0.605844,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Putri Yeni',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Nurdin',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.545587,
    'latitude' => 0.576401,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Ramzita',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => '-',
    'jml_agt_keluarga' => 1,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.544319,
    'latitude' => 0.571488,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Ratna Wilis',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Bonari',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Cahaya Ilahi',
    'longitude' => 101.530038,
    'latitude' => 0.594083,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Ratnawati',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Edi Candra',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.547363,
    'latitude' => 0.57234,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Relince',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Efendi Pakpahan',
    'jml_agt_keluarga' => 8,
    'kelompokPKH' => 'Cahaya Ilahi',
    'longitude' => 101.496110,
    'latitude' => 0.592802,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Rita Ria Susanti',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Liyanto',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.543878,
    'latitude' => 0.570608,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Rosnilawati',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Arin',
    'jml_agt_keluarga' => 6,
    'kelompokPKH' => 'Wardini',
    'longitude' => 101.537178,
    'latitude' => 0.572547,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Rukiati',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Juwono',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Mawar',
    'longitude' => 101.507225,
    'latitude' => 0.591558,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Sarinah',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Indra Saputra',
    'jml_agt_keluarga' => 6,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.5366249,
    'latitude' => 0.572562,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Siti Aisyah',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Nursalim',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Wardini',
    'longitude' => 101.547718,
    'latitude' => 0.576977,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Sri Rahayu',
    'alamat' => 'Jl. Bangdes Okura',
    'nama_kepala_keluarga' => 'Joko Kurniawan',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Mawar',
    'longitude' => 101.519570,
    'latitude' => 0.604403,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Sukiyem',
    'alamat' => 'Jl. Bangdes Okura',
    'nama_kepala_keluarga' => 'Paimin',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Mawar',
    'longitude' => null,
    'latitude' => null,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Sumiati Eko',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Eko Supriadi',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Mawar',
    'longitude' => 101.503533,
    'latitude' => 0.589700,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Sumiati Jimi',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Jurimin',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.545587,
    'latitude' => 0.576401,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Sumiati Siman',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Siman',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.540240,
    'latitude' => 0.571195,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Sumiati Riana Sari',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Asril',
    'jml_agt_keluarga' => 6,
    'kelompokPKH' => 'Wardini',
    'longitude' => 101.5402824,
    'latitude' => 0.5712685,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Suprapti',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Gitok',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.542223,
    'latitude' => 0.57091,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Wardini (Ketua Kelompok)',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Atan Keok',
    'jml_agt_keluarga' => 6,
    'kelompokPKH' => 'Wardini',
    'longitude' => 101.543556,
    'latitude' => 0.570606,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Weni',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => '-',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Wardini',
    'longitude' => 101.547363,
    'latitude' => 0.57263,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Yuna Maharani',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Rudi Heri',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Wardini',
    'longitude' => 101.54574,
    'latitude' => 0.570813,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Yusmawati',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Budiono',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.538802,
    'latitude' => 0.57124,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Yusnaini',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Mijo',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Cahaya Ilahi',
    'longitude' => 101.500653,
    'latitude' => 0.59113,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Zarima',
    'alamat' => 'Jl. Bangdes Okura',
    'nama_kepala_keluarga' => 'Zulherman',
    'jml_agt_keluarga' => 4,
    'kelompokPKH' => 'Mawar',
    'longitude' => 101.51957,
    'latitude' => 0.604403,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],
[
    'id' => Str::uuid(),
    'nama' => 'Zubaidah',
    'alamat' => 'Jl. Raja Panjang Okura',
    'nama_kepala_keluarga' => 'Jonhor Amin',
    'jml_agt_keluarga' => 5,
    'kelompokPKH' => 'Karmi',
    'longitude' => 101.545565,
    'latitude' => 0.571356,
    'foto_rumah' => null,
    'created_at' => now(),
    'updated_at' => now(),
],

        ];

        DB::table('pendudukMiskin')->insert($data);
    }
}
