<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SktmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data=[ [
            'id' => '585f56ca-ecd1-11ee-95e5-2a57142798db',
            'user_id' => '585f56ca-ecd1-11ee-95e5-2a57142791d1',
            'nama' => "Muhammad Riga",
            'tujuan' => 'Beasiswa Pendidikan',
            'jenis_kelamin' => 'Laki-laki',
            'tempatLahir' => 'Kebumen',
            'tanggalLahir' => '1996-06-12',
            'agama' => 'Islam',
            'nik' => '12345678901234',
            'alamat' => 'Jl. Contoh Alamat No. 1',
            'pekerjaan' => 'Wiraswasta',
            'keterangan' => 'Permohonan SKTM untuk keperluan beasiswa.',
            'alasan' => null,
            'status' => 'Diajukan',
            'pengantar_rt_rw' => 'sktm/pengantar1.pdf',
            'kk' => 'sktm/kk1.jpg',
            'ktp' => 'sktm/ktp1.jpg',
            'surat_pernyataan' => 'sktm/pernyataan1.pdf',
            'created_at' => now(),
            'updated_at' => now(),
        ],[
            'id' => '0f3b1c70-ecce-11ee-9c0c-4b5a173f5d61',
            'user_id' => '585f56ca-ecd1-11ee-95e5-2a57142791d2',
            'nama' => "Siti Aisyah",
            'tujuan' => 'Keringanan Biaya Rumah Sakit',
            'jenis_kelamin' => 'Perempuan',
            'tempatLahir' => 'Purwokerto',
            'tanggalLahir' => '1998-02-20',
            'agama' => 'Islam',
            'nik' => '23456789012345',
             'pekerjaan' => 'Wiraswasta',
             'alamat' => 'Jl. Melati No. 15',
            'keterangan' => 'Permohonan SKTM untuk pengobatan.',
            'alasan' => null,
            'status' => 'Diajukan',
            'pengantar_rt_rw' => 'sktm/pengantar2.pdf',
            'kk' => 'sktm/kk2.jpg',
            'ktp' => 'sktm/ktp2.jpg',
            'surat_pernyataan' => 'sktm/pernyataan2.pdf',
            'created_at' => now(),
            'updated_at' => now(),
        ],[
            'id' => '1679c5ae-ecce-11ee-9d3b-7a15bc729f72',
            'user_id' => '585f56ca-ecd1-11ee-95e5-2a57142791d3',
            'nama' => "Ahmad Fauzi",
            'tujuan' => 'Bantuan Sosial',
            'jenis_kelamin' => 'Laki-laki',
            'tempatLahir' => 'Cilacap',
            'tanggalLahir' => '1994-09-15',
            'agama' => 'Islam',
            'nik' => '34567890123456',
             'pekerjaan' => 'Wiraswasta',
             'alamat' => 'Jl. Kenanga No. 3',
            'keterangan' => 'Permohonan SKTM untuk bantuan sosial.',
            'alasan' => null,
            'status' => 'Diproses',
            'pengantar_rt_rw' => 'sktm/pengantar3.pdf',
            'kk' => 'sktm/kk3.jpg',
            'ktp' => 'sktm/ktp3.jpg',
            'surat_pernyataan' => 'sktm/pernyataan3.pdf',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'id' => '1e2226e6-ecce-11ee-a551-dc65d81bdab0',
            'user_id' => '585f56ca-ecd1-11ee-95e5-2a57142791d4',
            'nama' => "Lina Marlina",
            'tujuan' => 'Pengajuan KIP Kuliah',
            'jenis_kelamin' => 'Perempuan',
            'tempatLahir' => 'Yogyakarta',
            'tanggalLahir' => '2000-07-07',
            'agama' => 'Islam',
            'nik' => '45678901234567',
             'pekerjaan' => 'Wiraswasta',
             'alamat' => 'Jl. Mawar No. 12',
            'keterangan' => 'Permohonan SKTM untuk KIP Kuliah.',
            'alasan' => null,
            'status' => 'Diproses',
            'pengantar_rt_rw' => 'sktm/pengantar4.pdf',
            'kk' => 'sktm/kk4.jpg',
            'ktp' => 'sktm/ktp4.jpg',
            'surat_pernyataan' => 'sktm/pernyataan4.pdf',
            'created_at' => now(),
            'updated_at' => now(),
        ],[
            'id' => '25e3f6bc-ecce-11ee-89f9-8a45e10242a3',
            'user_id' => '585f56ca-ecd1-11ee-95e5-2a57142791db',
            'nama' => "Budi Hartono",
            'tujuan' => 'Pengajuan Bantuan UKM',
            'jenis_kelamin' => 'Laki-laki',
            'tempatLahir' => 'Magelang',
            'tanggalLahir' => '1985-12-12',
            'agama' => 'Kristen',
            'nik' => '56789012345678',
             'pekerjaan' => 'Wiraswasta',
             'alamat' => 'Jl. Flamboyan No. 20',
            'keterangan' => 'Permohonan SKTM untuk bantuan UKM.',
            'alasan' => 'Data Tidak lengkap',
            'status' => 'Ditolak',
            'pengantar_rt_rw' => 'sktm/pengantar5.pdf',
            'kk' => 'sktm/kk5.jpg',
            'ktp' => 'sktm/ktp5.jpg',
            'surat_pernyataan' => 'sktm/pernyataan5.pdf',
            'created_at' => now(),
            'updated_at' => now(),
        ], [
            'id' => '2d778ccc-ecce-11ee-9876-8b351aa5210e',
            'user_id' => '585f56ca-ecd1-11ee-95e5-2a57142791d5',
            'nama' => "Desi Kartika",
            'tujuan' => 'Beasiswa Sekolah Dasar',
            'jenis_kelamin' => 'Perempuan',
            'tempatLahir' => 'Banyumas',
            'tanggalLahir' => '2013-04-25',
            'agama' => 'Hindu',
            'nik' => '67890123456789',
             'pekerjaan' => 'Wiraswasta',
             'alamat' => 'Jl. Cempaka No. 5',
            'keterangan' => 'Permohonan SKTM untuk sekolah dasar.',
            'alasan' => null,
            'status' => 'Diajukan',
            'pengantar_rt_rw' => 'sktm/pengantar6.pdf',
            'kk' => 'sktm/kk6.jpg',
            'ktp' => 'sktm/ktp6.jpg',
            'surat_pernyataan' => 'sktm/pernyataan6.pdf',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => '34fe4ac8-ecce-11ee-b3d2-f01fa2aa881c',
            'user_id' => '585f56ca-ecd1-11ee-95e5-2a57142791d6',
            'nama' => "Teguh Prakoso",
            'tujuan' => 'Subsidi Listrik',
            'jenis_kelamin' => 'Laki-laki',
            'tempatLahir' => 'Solo',
            'tanggalLahir' => '1990-10-10',
            'agama' => 'Katolik',
            'nik' => '78901234567890',
             'pekerjaan' => 'Wiraswasta',
             'alamat' => 'Jl. Sudirman No. 18',
            'keterangan' => 'Permohonan SKTM untuk subsidi listrik.',
            'alasan' => null,
            'status' => 'Diproses',
            'pengantar_rt_rw' => 'sktm/pengantar7.pdf',
            'kk' => 'sktm/kk7.jpg',
            'ktp' => 'sktm/ktp7.jpg',
            'surat_pernyataan' => 'sktm/pernyataan7.pdf',
            'created_at' => now(),
            'updated_at' => now(),
        ],[
            'id' => '3cf9fa38-ecce-11ee-ae23-d083fcb0c4fb',
            'user_id' => '585f56ca-ecd1-11ee-95e5-2a57142791d7',
            'nama' => "Yuni Andriyani",
            'tujuan' => 'Keringanan Biaya Sekolah',
            'jenis_kelamin' => 'Perempuan',
            'tempatLahir' => 'Tegal',
            'tanggalLahir' => '2005-03-18',
            'agama' => 'Islam',
            'nik' => '89012345678901',
             'pekerjaan' => 'Wiraswasta',
             'alamat' => 'Jl. Mangga No. 9',
            'keterangan' => 'Permohonan SKTM untuk keringanan SPP.',
            'alasan' => null,
            'status' => 'Selesai',
            'pengantar_rt_rw' => 'sktm/pengantar8.pdf',
            'kk' => 'sktm/kk8.jpg',
            'ktp' => 'sktm/ktp8.jpg',
            'surat_pernyataan' => 'sktm/pernyataan8.pdf',
            'created_at' => now(),
            'updated_at' => now(),
        ],
        [
            'id' => '447299d8-ecce-11ee-8c11-7076cfa9e9e6',
            'user_id' => '585f56ca-ecd1-11ee-95e5-2a57142791d8',
            'nama' => "Arif Maulana",
            'tujuan' => 'Bantuan Rehabilitasi Rumah',
            'jenis_kelamin' => 'Laki-laki',
            'tempatLahir' => 'Banjarnegara',
            'tanggalLahir' => '1978-11-30',
            'agama' => 'Islam',
            'nik' => '90123456789012',
             'pekerjaan' => 'Wiraswasta',
             'alamat' => 'Jl. Nangka No. 4',
            'keterangan' => 'Permohonan SKTM untuk rehab rumah.',
            'status' => 'Diajukan',
             'alasan' => 'Data KK tidak valid',
            'pengantar_rt_rw' => 'sktm/pengantar9.pdf',
            'kk' => 'sktm/kk9.jpg',
            'ktp' => 'sktm/ktp9.jpg',
            'surat_pernyataan' => 'sktm/pernyataan9.pdf',
            'created_at' => '2025-07-01 10:30:00',
            'updated_at' => now(),
        ],
         [
            'id' => '4be0c0de-ecce-11ee-b70a-4c528e1d1c3f',
            'user_id' => '585f56ca-ecd1-11ee-95e5-2a57142791d9',
            'nama' => "Nia Ramadhani",
            'tujuan' => 'Keringanan Uang Pangkal Kuliah',
            'jenis_kelamin' => 'Perempuan',
            'tempatLahir' => 'Purworejo',
            'tanggalLahir' => '2001-05-05',
            'agama' => 'Islam',
            'nik' => '91234567890123',
             'pekerjaan' => 'Wiraswasta',
             'alamat' => 'Jl. Anggrek No. 7',
            'keterangan' => 'Permohonan SKTM untuk kuliah.',
            'status' => 'Diproses',
            'alasan' => null,
            'pengantar_rt_rw' => 'sktm/pengantar10.pdf',
            'kk' => 'sktm/kk10.jpg',
            'ktp' => 'sktm/ktp10.jpg',
            'surat_pernyataan' => 'sktm/pernyataan10.pdf',
            'created_at' => now(),
            'updated_at' => now(),
        ]];


        DB::table('sktm')->insert($data);
    }
}
