<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;


class SkuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('sku')->insert([
            [
                'id' => 'e5f5e556-ecce-11ee-9c0c-4b5a173f5d66',
                'nama' => 'Siti Aminah',
                'tujuan' => 'Modal Usaha',
                'jenis_kelamin' => 'Perempuan',
                'tempatLahir' => 'Pekanbaru',
                'tanggalLahir' => '1990-04-10',
                'agama' => 'Islam',
                'nik' => '1371012345678910',
                'pekerjaan' => 'Petani',
                'jenis_usaha' => 'Kebun Sawit',
                'tempat_usaha' => 'Desa Rimbo Panjang',
                'kelurahan' => 'Tampan',
                'kecamatan' => 'Payung Sekaki',
                'kota' => 'Pekanbaru',
                'alamat' => 'Jl. Sawit No. 12',
                'keterangan' => 'Pengembangan kebun sawit rakyat.',
                'status' => 'Selesai',
                'foto_usaha' => 'sku/foto_usaha6.jpg',
                'pengantar_rt_rw' => 'sku/pengantar6.pdf',
                'kk' => 'sku/kk6.jpg',
                'ktp' => 'sku/ktp6.jpg',
                'surat_pernyataan' => 'sku/pernyataan6.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'e5f5e557-ecce-11ee-9c0c-4b5a173f5d67',
                'nama' => 'Rahmat Hidayat',
                'tujuan' => 'Permodalan Pertanian',
                'jenis_kelamin' => 'Laki-laki',
                'tempatLahir' => 'Pekanbaru',
                'tanggalLahir' => '1985-08-22',
                'agama' => 'Islam',
                'nik' => '1371012345678920',
                'pekerjaan' => 'Petani',
                'jenis_usaha' => 'Kebun Cabai',
                'tempat_usaha' => 'Kecamatan Tenayan Raya',
                'kelurahan' => 'Sialang Rampai',
                'kecamatan' => 'Tenayan Raya',
                'kota' => 'Pekanbaru',
                'alamat' => 'Jl. Cabai Merah No. 5',
                'keterangan' => 'Untuk pembibitan cabai musim tanam baru.',
                'status' => 'Diajukan',
                'foto_usaha' => 'sku/foto_usaha7.jpg',
                'pengantar_rt_rw' => 'sku/pengantar7.pdf',
                'kk' => 'sku/kk7.jpg',
                'ktp' => 'sku/ktp7.jpg',
                'surat_pernyataan' => 'sku/pernyataan7.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'e5f5e558-ecce-11ee-9c0c-4b5a173f5d68',
                'nama' => 'Dewi Lestari',
                'tujuan' => 'Program Ketahanan Pangan',
                'jenis_kelamin' => 'Perempuan',
                'tempatLahir' => 'Pekanbaru',
                'tanggalLahir' => '1992-12-12',
                'agama' => 'Islam',
                'nik' => '1371012345678930',
                'pekerjaan' => 'Petani',
                'jenis_usaha' => 'Kebun Jagung',
                'tempat_usaha' => 'Kelurahan Sidomulyo Timur',
                'kelurahan' => 'Sidomulyo Timur',
                'kecamatan' => 'Marpoyan Damai',
                'kota' => 'Pekanbaru',
                'alamat' => 'Jl. Jagung Manis No. 8',
                'keterangan' => 'Untuk mendukung ketahanan pangan lokal.',
                'status' => 'Diproses',
                'foto_usaha' => 'sku/foto_usaha8.jpg',
                'pengantar_rt_rw' => 'sku/pengantar8.pdf',
                'kk' => 'sku/kk8.jpg',
                'ktp' => 'sku/ktp8.jpg',
                'surat_pernyataan' => 'sku/pernyataan8.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'e5f5e559-ecce-11ee-9c0c-4b5a173f5d69',
                'nama' => 'Andi Setiawan',
                'tujuan' => 'Pembibitan Sayur Organik',
                'jenis_kelamin' => 'Laki-laki',
                'tempatLahir' => 'Pekanbaru',
                'tanggalLahir' => '1987-06-06',
                'agama' => 'Islam',
                'nik' => '1371012345678940',
                'pekerjaan' => 'Petani',
                'jenis_usaha' => 'Kebun Sayur',
                'tempat_usaha' => 'Kecamatan Rumbai',
                'kelurahan' => 'Rumbai Bukit',
                'kecamatan' => 'Rumbai',
                'kota' => 'Pekanbaru',
                'alamat' => 'Jl. Sayur Lestari No. 10',
                'keterangan' => 'Untuk usaha sayur organik rumahan.',
                'status' => 'Selesai',
                'foto_usaha' => 'sku/foto_usaha9.jpg',
                'pengantar_rt_rw' => 'sku/pengantar9.pdf',
                'kk' => 'sku/kk9.jpg',
                'ktp' => 'sku/ktp9.jpg',
                'surat_pernyataan' => 'sku/pernyataan9.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'e5f5e560-ecce-11ee-9c0c-4b5a173f5d70',
                'nama' => 'Nurul Huda',
                'tujuan' => 'Budidaya Ikan Lele',
                'jenis_kelamin' => 'Laki-laki',
                'tempatLahir' => 'Pekanbaru',
                'tanggalLahir' => '1991-03-15',
                'agama' => 'Islam',
                'nik' => '1371012345678950',
                'pekerjaan' => 'Peternak',
                'jenis_usaha' => 'Ternak Lele',
                'tempat_usaha' => 'Kelurahan Limbungan',
                'kelurahan' => 'Limbungan',
                'kecamatan' => 'Rumbai Pesisir',
                'kota' => 'Pekanbaru',
                'alamat' => 'Jl. Kolam Lele No. 3',
                'keterangan' => 'Untuk pengembangan kolam lele baru.',
                'status' => 'Diajukan',
                'foto_usaha' => 'sku/foto_usaha10.jpg',
                'pengantar_rt_rw' => 'sku/pengantar10.pdf',
                'kk' => 'sku/kk10.jpg',
                'ktp' => 'sku/ktp10.jpg',
                'surat_pernyataan' => 'sku/pernyataan10.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 'f6f6f666-ecce-11ee-9c0c-4b5a173f5d71',
                'nama' => 'Ahmad Yusuf',
                'tujuan' => 'Pengajuan SK Usaha',
                'jenis_kelamin' => 'Laki-laki',
                'tempatLahir' => 'Kebumen',
                'tanggalLahir' => '1990-05-21',
                'agama' => 'Islam',
                'nik' => '3276012345678901',
                'pekerjaan' => 'Wiraswasta',
                'jenis_usaha' => 'Warung Sembako',
                'tempat_usaha' => 'Jl. Merpati No. 10',
                'kelurahan' => 'Limbungan',
                'kecamatan' => 'Rumbai Pesisir',
                'kota' => 'Pekanbaru',
                'alamat' => 'Jl. Melati No. 15',
                'keterangan' => 'Digunakan untuk bantuan UMKM.',
                'status' => 'Diproses',
                'foto_usaha' => 'sku/foto_usaha1.jpg',
                'pengantar_rt_rw' => 'sku/pengantar1.pdf',
                'kk' => 'sku/kk1.jpg',
                'ktp' => 'sku/ktp1.jpg',
                'surat_pernyataan' => 'sku/pernyataan1.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'f7f7f777-ecce-11ee-9c0c-4b5a173f5d72',
                'nama' => 'Dewi Lestari',
                'tujuan' => 'Legalitas Usaha',
                'jenis_kelamin' => 'Perempuan',
                'tempatLahir' => 'Purwokerto',
                'tanggalLahir' => '1992-03-15',
                'agama' => 'Islam',
                'nik' => '3276012345678902',
                'pekerjaan' => 'Wiraswasta',
                'jenis_usaha' => 'Laundry',
                'tempat_usaha' => 'Jl. Kenanga No. 12',
                'kelurahan' => 'Limbungan Baru',
                'kecamatan' => 'Rumbai Pesisir',
                'kota' => 'Pekanbaru',
                'alamat' => 'Jl. Anggrek No. 3',
                'keterangan' => 'Untuk syarat surat domisili.',
                'status' => 'Selesai',
                'foto_usaha' => 'sku/foto_usaha2.jpg',
                'pengantar_rt_rw' => 'sku/pengantar2.pdf',
                'kk' => 'sku/kk2.jpg',
                'ktp' => 'sku/ktp2.jpg',
                'surat_pernyataan' => 'sku/pernyataan2.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'f8f8f888-ecce-11ee-9c0c-4b5a173f5d73',
                'nama' => 'Rizky Hidayat',
                'tujuan' => 'Modal Usaha',
                'jenis_kelamin' => 'Laki-laki',
                'tempatLahir' => 'Banyumas',
                'tanggalLahir' => '1994-07-30',
                'agama' => 'Islam',
                'nik' => '3276012345678903',
                'pekerjaan' => 'Wiraswasta',
                'jenis_usaha' => 'Barbershop',
                'tempat_usaha' => 'Jl. Raya Selatan No. 5',
                'kelurahan' => 'Sri Meranti',
                'kecamatan' => 'Rumbai Pesisir',
                'kota' => 'Pekanbaru',
                'alamat' => 'Jl. Mawar No. 18',
                'keterangan' => 'Surat ini digunakan untuk keperluan bank.',
                'status' => 'Diajukan',
                'foto_usaha' => 'sku/foto_usaha3.jpg',
                'pengantar_rt_rw' => 'sku/pengantar3.pdf',
                'kk' => 'sku/kk3.jpg',
                'ktp' => 'sku/ktp3.jpg',
                'surat_pernyataan' => 'sku/pernyataan3.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'f9f9f999-ecce-11ee-9c0c-4b5a173f5d74',
                'nama' => 'Siti Nurhaliza',
                'tujuan' => 'Pendataan UMKM',
                'jenis_kelamin' => 'Perempuan',
                'tempatLahir' => 'Kebumen',
                'tanggalLahir' => '1993-10-10',
                'agama' => 'Islam',
                'nik' => '3276012345678904',
                'pekerjaan' => 'Wiraswasta',
                'jenis_usaha' => 'Warung Makan',
                'tempat_usaha' => 'Jl. Pahlawan No. 33',
                'kelurahan' => 'Tebing Tinggi Okura',
                'kecamatan' => 'Rumbai Pesisir',
                'kota' => 'Pekanbaru',
                'alamat' => 'Jl. Bima No. 10',
                'keterangan' => 'Pendataan usaha baru.',
                'status' => 'Diproses',
                'foto_usaha' => 'sku/foto_usaha4.jpg',
                'pengantar_rt_rw' => 'sku/pengantar4.pdf',
                'kk' => 'sku/kk4.jpg',
                'ktp' => 'sku/ktp4.jpg',
                'surat_pernyataan' => 'sku/pernyataan4.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 'g0g0g000-ecce-11ee-9c0c-4b5a173f5d75',
                'nama' => 'Budi Santoso',
                'tujuan' => 'Pengajuan Bantuan',
                'jenis_kelamin' => 'Laki-laki',
                'tempatLahir' => 'Purworejo',
                'tanggalLahir' => '1988-11-11',
                'agama' => 'Islam',
                'nik' => '3276012345678905',
                'pekerjaan' => 'Wiraswasta',
                'jenis_usaha' => 'Jasa Cuci Motor',
                'tempat_usaha' => 'Jl. Cempaka No. 17',
                'kelurahan' => 'Meranti Pandak',
                'kecamatan' => 'Rumbai Pesisir',
                'kota' => 'Pekanbaru',
                'alamat' => 'Jl. Duren No. 1',
                'keterangan' => 'Untuk pengajuan program UMKM.',
                'status' => 'Selesai',
                'foto_usaha' => 'sku/foto_usaha5.jpg',
                'pengantar_rt_rw' => 'sku/pengantar5.pdf',
                'kk' => 'sku/kk5.jpg',
                'ktp' => 'sku/ktp5.jpg',
                'surat_pernyataan' => 'sku/pernyataan5.pdf',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
